import { setGlobalLDContext } from '@/ld/globals';
import NextClient from '@/ld/nextClient';
import LDProvider from '@/ld/provider/LDProvider';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// In production, contexts should be obtained from cookies.
// We are hard-coding the context here as a contrived example.
const context = { kind: 'user', key: 'nextjs-user-1' };

// Save the context globally and get the bootstrap values for the context
// to pass to LDProvider.
const bootstrap = await setGlobalLDContext(context);

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LDProvider context={context} options={{ bootstrap }}>
          {children}
        </LDProvider>
      </body>
    </html>
  );
}
