import LDProvider from '@/ld/provider/LDProvider';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const context = { kind: 'user', key: 'nextjs-user-1' }; // await getLDContext();
  // const ldc = NextClient.get();
  // const bootstrap = await ldc.allFlags();

  return (
    <html lang="en">
      <body className={inter.className}>
        <LDProvider context={context}>{children}</LDProvider>
      </body>
    </html>
  );
}
